trigger:
  branches:
    include:
    - main  # Trigger the pipeline when changes are pushed to the 'main' branch
    - develop/vNext  # Trigger the pipeline when changes are pushed to the 'develop' branch
    - feature/*  # Trigger branches that start with "feature/"
    exclude:
    - personal/*  # Exclude branches that start with "personal/"

pool:
  vmImage: 'windows-latest'  # You can choose an appropriate VM image

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - script: echo "Building the application"
    # Add your build steps here

- stage: Test
  jobs:
  - job: Test
    steps:
    - script: echo "Running tests"
    # Add your test steps here